[package]
authors = ["arussell123@gmail.com"]
build = "build.rs"
name = "website"
version = "0.1.0"

[[bin]]
doc = false
name = "main"

[dependencies]
chrono = "0.2.19"
docopt = "0.6.78"
docopt_macros = "0.6.80"
dotenv = "0.8.0"
dotenv_macros = "0.8.0"
env_logger = "0.3.2"
handlebars = "0.16.0"
handlebars-iron = "0.13.1"
hoedown = "3.0.3"
hyper = "0.8.0"
iron = "0.2.6"
lazy_static = "0.1.15"
log = "0.3.5"
maplit = "0.1.3"
mount = "0.0.10"
persistent = "0.0.9"
quick-error = "1.0.0"
router = "0.1.0"
rustc-serialize = "0.3.16"
serde = "0.7.0"
serde_json = "0.7.0"
serde_macros = "0.7.0"
staticfile = "0.1.0"
toml = "0.1.26"
yaml-rust = "0.3.0"

[dependencies.ammonia]
git = "https://github.com/notriddle/ammonia"

[dependencies.clippy]
version = "*"
optional = true

[dependencies.regex]
features = ["pattern"]
version = "0.1.48"

[dependencies.url]
features = ["serde_serialization"]
version = "0.5.5"

[features]
default = ["handlebars-iron/unstable"]
watch = ["handlebars-iron/watch"]
