[package]
authors = ["arussell123@gmail.com"]
build = "build.rs"
name = "website"
version = "0.1.0"

[[bin]]
doc = false
name = "main"

[dependencies]
ammonia = "0.3"
clap = "2"
dotenv = "0.10"
dotenv_macros = "0.10"
derive-error-chain = "0.10"
env_logger = "0.4"
error-chain = "0.10"
hoedown = "6"
handlebars-iron = "0.24"
hubcaps = "0.3"
hyper = "0.10"
hyper-native-tls = "0.2"
iron = "0.5"
log = "0.3.5"
mount = "0.3"
params = "0.6"
persistent = "0.3"
r2d2 = "0.7"
r2d2_sqlite = "0.2"
router = "0.5"
serde = "1"
serde_json = "1"
serde_derive = "1"
serde_yaml = "0.7"
staticfile = "0.4"
toml = "0.4"
url = "1.1"
url_serde = "0.2"

[dependencies.chrono]
features = ["serde"]
version = "0.3"

[dependencies.rusqlite]
features = ["chrono"]
version = "0.11"

[dev-dependencies]
iron-test = "0.5"
tempfile = "2.0.0"

[features]
watch = ["handlebars-iron/watch"]
