[package]
authors = ["arussell123@gmail.com"]
build = "build.rs"
name = "website"
version = "0.1.0"

[[bin]]
doc = false
name = "main"

[dependencies]
ammonia = "0.1.2"
docopt = "0.6.78"
docopt_macros = "0.6.80"
dotenv = "0.8.0"
dotenv_macros = "0.9.0"
env_logger = "0.3.2"
hoedown = "5.0.0"
hyper = "0.9.5"
iron = "0.4.0"
lazy_static = "0.2.1"
log = "0.3.5"
maplit = "0.1.3"
mount = "0.2.0"
persistent = "0.2.0"
quick-error = "1.0.0"
router = "0.2.0"
rustc-serialize = "0.3.16"
serde = "0.8.0"
serde_json = "0.8.0"
serde_macros = "0.8.0"
serde_yaml = "0.4.0"
staticfile = "0.3.0"
toml = "0.2.0"

[dependencies.chrono]
features = ["serde"]
version = "0.2.19"

[dependencies.clippy]
optional = true
version = "*"

[dependencies.handlebars]
default_features = false
features = ["serde_type"]
version = "0.20.0"

[dependencies.handlebars-iron]
default_features = false
features = ["serde_type"]
version = "0.18.0"

[dependencies.regex]
features = ["pattern"]
version = "0.1.48"

[dependencies.rusqlite]
features = ["chrono"]
version = "0.7.2"

[dependencies.url]
features = ["serde"]
version = "1.1.0"

[dev-dependencies]
iron-test = "0.4"

[features]
watch = ["handlebars-iron/watch"]
