[package]
authors = ["arussell123@gmail.com"]
build = "build.rs"
name = "website"
version = "0.1.0"

[[bin]]
doc = false
name = "main"

[dependencies]
ammonia = "0.1.2"
clap = "2"
dotenv = "0.9"
dotenv_macros = "0.10"
env_logger = "0.3.2"
error-chain = "0.5.0"
hoedown = "5.0.0"
hyper = "0.9.5"
iron = "0.5"
log = "0.3.5"
mount = "0.3"
params = "0.6"
persistent = "0.3"
r2d2 = "0.7"
router = "0.5"
serde = "0.9"
serde_json = "0.9"
serde_derive = "0.9"
serde_yaml = "0.6"
staticfile = "0.4"
toml = "0.2.0"

[dependencies.chrono]
features = ["serde"]
version = "0.3"

[dependencies.handlebars]
default_features = false
features = ["serde_type"]
version = "0.25"

[dependencies.handlebars-iron]
default_features = false
features = ["serde_type", "partial_legacy"]
version = "0.23"

[dependencies.hubcaps]
default_features = false
features = ["nightly"]
git = "https://github.com/euclio/hubcaps"

[dependencies.r2d2_sqlite]
git = "https://github.com/liveresume/r2d2-sqlite"
branch = "patch-1"

[dependencies.rusqlite]
features = ["chrono"]
version = "0.10"

[dependencies.url]
features = ["serde"]
version = "1.1.0"

[dev-dependencies]
iron-test = "0.5"
tempfile = "2.0.0"

[features]
watch = ["handlebars-iron/watch"]
