[package]
authors = ["arussell123@gmail.com"]
build = "build.rs"
name = "website"
version = "0.1.0"

[[bin]]
doc = false
name = "main"

[dependencies]
chrono = "0.2.19"
clippy = "0.0.44"
docopt = "0.6.78"
docopt_macros = "0.6.80"
dotenv = "0.8.0"
dotenv_macros = "0.8.0"
env_logger = "0.3.2"
handlebars = "0.14.0"
handlebars-iron = "0.11.0"
hoedown = "3.0.3"
hyper = "0.7.2"
iron = "0.2.6"
lazy_static = "0.1.15"
log = "0.3.5"
maplit = "0.1.3"
mount = "0.0.9"
persistent = "0.0.9"
quick-error = "0.2.2"
regex_macros = "0.1.28"
router = "0.1.0"
rustc-serialize = "0.3.16"
serde = "0.6.11"
serde_json = "0.6.0"
serde_macros = "0.6.11"
staticfile = "0.1.0"
toml = "0.1.26"
yaml-rust = "0.3.0"

[dependencies.ammonia]
git = "https://github.com/notriddle/ammonia"

[dependencies.regex]
features = ["pattern"]
version = "0.1.48"

[features]
default = ["handlebars-iron/serde_type"]
watch = ["handlebars-iron/watch"]
