DROP TABLE IF EXISTS posts;
DROP TABLE IF EXISTS post_content;

CREATE TABLE IF NOT EXISTS posts (
    id      INTEGER PRIMARY KEY,
    title   VARCHAR NOT NULL,
    date    DATETIME NOT NULL,
    html    VARCHAR NOT NULL,
    summary VARCHAR(250) NOT NULL,
    url     VARCHAR(100) NOT NULL,
    slug    VARCHAR NOT NULL
);
